# Generated by Django 4.2.2 on 2023-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
