# Generated by Django 4.2.2 on 2023-11-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_event_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="profile_photos/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="position",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
