# Generated by Django 4.2.2 on 2023-11-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_userprofile_photo_alter_userprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
